Add new actions to get sales, reports and downloads reviews from App Store Connect API
masmovil/fastlane-plugin-mm_toolkit pull request #6
Opened 2023-05-05 13:03 UTC by r-pedraza

### PR's key points
Added the actions to download reports and sales and reviews.

I have also added several models that represent the data structure and reduce the complexity by being able to handle the data more easily.

### How to review this PR?
Talk with me.

2023-05-08 06:53 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/actions/download_reviews_from_app_store_connect.rb
> +          :source_control
Set this to
```suggestion
          :app_store_connect
```

2023-05-08 06:53 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/actions/download_sales_and_reports_from_app_store_connect.rb
> +          :source_control
Set this to
```suggestion
          :app_store_connect
```

2023-05-16 14:33 UTC, adriangl requested changes
There are a few things missing, apart from the comments:
- You have to run `rubocop` in order to lint the code. Run:
  ```shell
  bundle exec rubocop -A
  ```
  So the code gets auto-corrected, and fix the missing uncorrected issues
- You have to bump the plug-in version at https://github.com/masmovil/fastlane-plugin-mm_toolkit/blob/master/lib/fastlane/plugin/mm_toolkit/version.rb so consumers can pick up the proper version.

2023-05-16 14:33 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/helper/app_store_ax_connector/app_store_connect_api.rb
> +end
Might be worth condensing this into:
```ruby
require 'uri' # at the start of the file

def sales_reports_url(date)
  path = "salesReports"
  query_params = {
    "filter[frequency]" => "DAILY",
    "filter[reportDate]" => date,
    "filter[reportType]" => "SALES",
    "filter[reportSubType]" => "SUMMARY",
    "filter[vendorNumber]" => "#{@vendor_number}"
  }
  query = URI.encode_www_form(query_params)

  URI::HTTP.build(host: base_url, path: path, query: query)
end
```

Give it a try! ;)

2023-05-16 14:33 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/helper/app_store_ax_connector/reviews.rb
> +        puts file
```suggestion
```

2023-05-17 06:50 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/actions/download_reviews_from_app_store_connect.rb
> +            }
Again, you won't need this code 😛 
```suggestion
```

2023-05-19 13:21 UTC, adriangl requested changes

2023-05-19 13:21 UTC, adriangl commented on lib/fastlane/plugin/mm_toolkit/actions/download_reviews_from_app_store_connect.rb
> +          }
Don't forget removing this code!!
```suggestion
```

2023-05-22 09:42 UTC, adriangl submitted a review, later dismissed

2023-05-23 11:05 UTC, adriangl approved these changes

2023-05-31 11:48 UTC, josemanuelmartin approved these changes

2023-06-05 08:41 UTC, sebastianvarela approved these changes

2023-06-05 15:33 UTC, adriangl approved these changes

2023-06-05 15:34 UTC, merged