Remove V from version name
masmovil/fastlane-plugin-mm_toolkit pull request #9
Opened 2023-09-15 08:23 UTC by nicolasmertanen

### PR's key points
This PR removes the "v" from the version name, not to be included in the app nor in the version tags.
 
### How to review this PR?
You can run `tag_train` locally with `push_to_repo:false` to test this.

2023-09-15 09:55 UTC, albertobaezap approved these changes

2023-09-18 10:28 UTC, finxo approved these changes

2023-09-18 10:47 UTC, adriangl requested changes
Don't forget bumping the version in `lib/fastlane/plugin/version.rb`!

2023-09-18 13:31 UTC, nicolasmertanen commented
> Don't forget bumping the version in `lib/fastlane/plugin/version.rb`!

8a35699286f26191b9861c961f20e382ff1310fc

2023-09-19 08:09 UTC, sebastianvarela approved these changes

2023-09-19 08:18 UTC, sebastianvarela commented
A note: The version increase would be more elegant if it went in another PR to isolate the functionality of the release

2023-09-19 09:33 UTC, r-pedraza approved these changes

2023-09-19 15:32 UTC, adriangl commented
> A note: The version bump would be more elegant if it went in another PR to isolate the functionality of the release

It would make sense if we made more streamlined releases (aka: a proper Changelog, a proper Github release and all that stuff). I'd say it's OK for now as the version is only going to contain this, but I agree about doing this if we're going to have more frequent updates and contributors 😛

2023-09-19 15:33 UTC, adriangl approved these changes

2023-10-02 10:16 UTC, merged